config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists do
    resources :clues
  end
  devise_for :users
  post "/lists/:list_id/clues/:id", to: "clues#validate", as: :validate_answer
  post "/clues", to: "clues#answer"
  get "/lists/:list_id/newcluefromaddress", to: "clues#new_from_address", as: :new_from_address
  post "/lists/:list_id/newcluefromaddress", to: "clues#create_from_address", as: :create_from_address
  post "/", to: "lists#reset_current_clue", as: :reset_current_clue
end

app/models/address.rb
class Address

  def initialize(address)
    @address = address.join(" ")
  end

  def geocoder_knows?
    !(Geocoder.search(@address) == [])
  end

  def coordinates
    {latitude: Geocoder.search(@address)[0].latitude, longitude: Geocoder.search(@address)[0].longitude}
  end

end

app/models/clue.rb
class Clue < ActiveRecord::Base
  belongs_to :list
  belongs_to :game
  has_many :users

  def next_clue
    self.list.clues[self.list.clues.index(self) + 1]
  end

  def last_clue?
    self == self.list.clues.last ? true : false
  end

  def submission_valid?(user_answer, user_location=nil)
    !!(answer_valid?(user_answer) && location_valid?(user_location))
  end

  def location_valid?(user_location=nil)
    return true
    clue_location = [latitude, longitude]
    distance = Geocoder::Calculations.distance_between(user_location, clue_location) * 5280
    distance <= 65 ? true : false
  end

  def answer_valid?(user_answer)
    word_match = FuzzyStringMatch::JaroWinkler.create( :pure )
    if word_match.getDistance("#{self.answer}".downcase, "#{user_answer}".downcase) > 0.65
      return true
    else
      return false
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_users
  has_many :users, through: :game_users
  belongs_to :list
  has_many :clues, through: :list

end

app/models/game_user.rb
class GameUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :clues
  has_many :games
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :clue
  has_many :game_users
  has_many :games, through: :game_users
  has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  respond_to :js

  def index
  end

  def new
    @list = List.find(params[:list_id])
    @clue = Clue.new
  end

  def create
    # binding.pry
    @clue = Clue.create({
      latitude: params["latitude"],
      longitude: params["longitude"],
      text: params["text"],
      answer: params["answer"],
      list_id: params["list_id"]
      })
    @list = List.find(params[:list_id])

    respond_to do |format|
      format.js { j render(:partial => "clue_panel")}
    end

  end

  def update
    @clue = Clue.find(params[:id])
    @clue.text = params[:text]
    @clue.answer = params[:answer]
    @clue.save

    respond_to do |format|
      format.json { render json: @clue.id }
    end
  end

  def destroy

    @clue = Clue.find(params[:id])
    @clue.destroy

    respond_to do |format|
      format.json { render json: @clue.id }
    end
  end

  def show
    # @list=List.find(params[:list_id])
    @clue = Clue.find(params[:id])
    current_user.clue_id = @clue.id
    current_user.save
  end

  def validate
    @clue = Clue.find(params[:id])
    user_answer = params[:answer]
    user_location = [params[:latitude], params[:longitude]]
    if params[:reset_clue_id] == "true"
      current_user.clue_id = nil
      current_user.save
      redirect_to root_path
    elsif @clue.submission_valid?(user_answer, user_location)
      if @clue.last_clue?
        flash[:notice] = "You win! Play again?"
        current_user.clue_id = nil
        current_user.save
        redirect_to root_path
      else
        @clue = @clue.next_clue
        redirect_to "/lists/#{@clue.list.id}/clues/#{@clue.id}"
      end
    else
      flash[:alert] = "Wrong answer, try again!"
      @clue = Clue.find(params[:id])
      redirect_to "/lists/#{@clue.list.id}/clues/#{@clue.id}"
    end
  end

  def new_from_address
    @list = List.find(params[:list_id])
  end

  def create_from_address
    # binding.pry
    address = params[:address][:street]
    city = params[:address][:city]
    state = params[:address][:state]
    zip = params[:address][:zip]

    @address = Address.new([address, city, state, zip])
    respond_to do |format|
      format.json { render json: @address.coordinates }
    end

    # if @address.geocoder_knows?
    #   binding.pry
    #   return @address.coordinates
    # end
  end

  private

  # @address = Address.new(["11 Broadway", "New York", "NY", "10004"])



end

app/controllers/game_controller.rb
class GameController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    if !!(current_user.clue_id)
      redirect_to "/lists/#{current_user.clue.list_id}/clues/#{current_user.clue_id}"
    end
  end

  def new
    @list = List.new
  end

  def create
    @list=List.create(name: params[:name], location: params[:location], creator: current_user.id)
    redirect_to "/lists/#{@list.id}/edit"
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.name = params[:name]
    @list.location = params[:location]
    @list.save

    respond_to do |format|
      format.json { render json: @list.id }
    end
  end

  def show
    @list=List.find(params[:id])
  end

  def reset_current_clue
    current_user.clue_id = nil
    current_user.save
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/clue_helper.rb
module ClueHelper

end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/clues/_all_clues.erb
<div id="all-clues">
  <% @list.clues.each do |clue| %>
    <div class= "clue-wrapper panel panel-default" id= <%="clue-#{clue.id}" %>>
      <div class="clue-info panel-heading">
        <div class="hidden clue-id"><%= "#{clue.id}" %></div>
        <div class="hidden list-id"><%= "#{clue.list.id}" %></div>
        <div class='clue-text '><%=  "Clue:  #{clue.text}" %></div>
        <div class='clue-answer'><%= "Answer:  #{clue.answer}" %></div>
      </div>
      <div class="panel-body">
        <div class= "icons clearfix">
          <div class= "edit"><%= image_tag("edit.png")%></div>
          <div class= "delete"><%= image_tag("delete.png")%></div>
        </div>
        <div class="edit_clue" style="display:none">
          Edit your clue using the form below.
          <%= form_tag("/list/#{@list.id}/clues", method: "post", class:"edit-clue-form") do %>
            <%= text_field_tag(:text, nil, value: clue.text, class: 'form-control') %><br>
            <%= text_field_tag(:answer, nil, value: clue.answer, class: 'form-control') %><br>
            <%= submit_tag("Update Clue", class: "btn btn-small") %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/clues/_clue.html.erb
<div id="question">
  <%= @clue.text %>
</div>

<div>
  <%= form_tag(validate_answer_path, id: "clue-answer-form", method: "post") do %>
    <%= text_field_tag(:answer) %>
    <%= hidden_field_tag "longitude" %>
    <%= hidden_field_tag "latitude" %>
    <%= submit_tag("Your Answer", id: "answer-button", class: "btn btn-white btn-lg") %>
  <% end %>
</div><br>

<div class="skip-button">
  <% if @clue.last_clue? %>
    <p>This is your last clue.</p>
    <%= form_tag(validate_answer_path, id: "skip-form", method: "post") do %>
      <%= hidden_field_tag "reset_clue_id", "true" %>
      <%= submit_tag("Skip", id: "skip-last-clue", class: "btn btn-white btn-lg") %>
    <% end %>
  <% else %>
    <% @clue = @clue.next_clue %>
    <%= link_to "Skip", "/lists/#{@clue.list.id}/clues/#{@clue.id}", method:"get", class: "btn btn-white btn-lg" %>
  <% end %>
</div>

app/views/clues/_clue_panel.html.erb
<div class= "clue-wrapper panel panel-default" id= <%="clue-#{@clue.id}" %>>
  <div class="clue-info panel-heading">
    <div class="hidden clue-id"><%= "#{@clue.id}" %></div>
    <div class="hidden list-id"><%= "#{@clue.list.id}" %></div>
    <div class="clue-text "><%=  "Clue:  #{@clue.text}" %></div>
    <div class="clue-answer"><%= "Answer:  #{@clue.answer}" %></div>
  </div>
  <div class="panel-body">
    <div class= "icons clearfix">
      <div class= "edit"><%= image_tag("edit.png")%></div>
      <div class= "delete"><%= image_tag("delete.png")%></div>
    </div>
    <div class="edit_clue" style="display:none">
      Edit your clue using the form below.
      <%= form_tag("/list/#{@list.id}/clues", method: "post", class:"edit-clue-form") do %>
        <%= text_field_tag(:text, nil, value: @clue.text, class: "form-control") %><br>
        <%= text_field_tag(:answer, nil, value: @clue.answer, class: "form-control") %><br>
        <%= submit_tag("Update Clue", class: "btn btn-small") %>
      <% end %>
    </div>
  </div>
</div>

app/views/clues/_edit_or_delete.erb
<div class= "clue-wrapper" id= <%="clue-#{clue.id}" %>>
  <div class="clue-info">
    <div class="hidden clue-id"><%= "#{clue.id}" %></div>
    <div class="hidden list-id"><%= "#{clue.list.id}" %></div>
    <div class='clue-text'><%= clue.text %></div>
    <div class='clue-answer'><%= clue.answer %></div>
  </div>
  <div class= "icons">
    <div class= "edit"><%= image_tag("edit.png")%></div>
    <div class= "delete"><%= image_tag("delete.png")%></div>
  </div>
</div>

app/views/clues/_new.html.erb
<%= form_tag("lists/#{@list.id}/clues", method: "post", id:"new-clue-form") do %>
  <%= text_area_tag(:text, nil, placeholder: 'Your Question') %><br>
  <%= text_field_tag(:answer, nil, placeholder: 'Enter Answer') %><br>
  <%= hidden_field_tag "list_id", "#{@list.id}" %>
  <%= hidden_field_tag "longitude" %>
  <%= hidden_field_tag "latitude" %>
  <%= hidden_field_tag "type", "on-the-go" %>
  <%= submit_tag("Submit Clue", class: "btn btn-white btn-lg") %>
<% end %>

app/views/clues/_new_from_address_form.html.erb
<%= form_tag("lists/#{@list.id}/clues", method: "post", id:"new-from-address") do %>
  <%= text_area_tag(:text, nil, placeholder: 'Enter your clue here.', required: true) %><br>
  <p>&nbsp;</p>
  <%= text_field_tag(:answer, nil, placeholder: 'Answer', required: true) %><br>
  <p>&nbsp;</p>
  <%= text_field_tag(:street, nil, placeholder: 'Street Address', required: true) %><br>
  <%= text_field_tag(:city, nil, placeholder: 'City', required: true) %><br>
  <%= text_field_tag(:state, nil, placeholder: 'State', required: true, pattern: '[a-zA-z]{2,}') %><br>
  <%= text_field_tag(:zip, nil, placeholder: 'Zip Code', required: true, pattern: '[\d]{5,}') %><br>
  <%= hidden_field_tag "list_id", "#{@list.id}" %>
  <%= hidden_field_tag "longitude" %>
  <%= hidden_field_tag "latitude" %>
  <%= hidden_field_tag "type", "from_address" %>
  <%= submit_tag("Create Clue", id: "create-clue-from-address", class: "btn btn-white btn-lg") %>
<% end %>

app/views/clues/create.js.erb
<%= j render(:partial => "clue_panel") %> 

app/views/clues/edit_clue.html.erb
<div class= "edit_clue">
  Edit your clue using the form below.
  <%= form_tag(list_clues_path, method: "post", class:"edit-clue-form") do %>
    <pre><%= text_field_tag(:text, nil, value: clue.text) %></pre>
    &nbsp;
    <pre><%= text_field_tag(:answer, nil, value: clue.answer) %></pre>
    <%= submit_tag("Submit Clue", class: "btn btn-white btn-lg") %>
  <% end %>
</div>

app/views/clues/new.html.erb
<div class="names-locations">
<p>
  Name: <%=@list.name %>
</p>
<p>
  Location: <%=@list.location %>
</p>
</div>

<div class="clue-list">
  <% if @list.clues.length>0 %>
  <%= render partial:"all_clues" %>
  <div id="new-clue-submit" >
    <%= link_to "I'm Done!", "/lists/#{@list}/clues", method:"get", class: "btn btn-white btn-lg" %>
  </div>
  <% end %>
</div>
<p>&nbsp;</p>

<div class="row">
  <div id="new-clue-form" class="col-xs-6">
    <%= render partial: "new" %>
  </div>

  <div id="new-clue-address-form" class="col-xs-6">
    <%= render partial: "new_from_address_form" %>
  </div>
</div>

app/views/clues/new_from_address.html.erb
<div class="names-locations">
<p>
Name: <%=@list.name %>
</p>
<p>
  Location: <%=@list.location %>
</p>
</div>

<div class="clue-list">
  <ol id="ol-clues">
  <% if @list.clues.length>0 %>
  <%= render partial:"all_clues" %>
  </ol>
  <div id="new-clue-submit" >
    <%= link_to "I'm Done!", "/lists/#{@list}/clues", method:"get", class: "btn btn-white btn-lg" %>
  </div>
  <% end %>
</div>

<%= render partial: 'new_from_address_form' %>

app/views/clues/show.html.erb
<div id="clue-form">
  <%= render @clue %>
</div>

<div id="test"></div>

app/views/clues/validate.html.erb
<%= render @clue %>

app/views/clues/validate.js.erb
<%= j render @clue %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ScavengerHuntProject1</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>

    <!-- Custom fonts -->
    <!-- <link href="css/ionicons.min.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/animate.min.css" rel="stylesheet" type="text/css"> -->

    <!-- Background Slider -->
    <!-- <link href="js/vegas/vegas.min.css" rel="stylesheet" type="text/css"> -->

    <!-- Custom CSS -->
    <!-- <link href="css/csoon.css" rel="stylesheet"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<!-- Preloader -->
<div id="preloader"><div id="status">&nbsp;</div></div>

<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" data-wow-duration="3s" data-wow-delay=".2s" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <div id="home-button">
        <%= link_to image_tag("star-8-32.png") + " Scavenger Hunt", reset_current_clue_path, method: :post %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1.4s">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <!-- <li class="hidden">
          <a href="#page-top"></a>
        </li> -->
        <!-- <li>
            <a class="page-scroll" href="#team">TEAM</a>
        </li> -->
        <% if user_signed_in? %>
          <!-- <li>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'page-scroll' %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'page-scroll'  %>
          </li>
          <li> -->
            <div class="">
              Logged in as <strong><%= current_user.email %></strong>.<br>
              <%= link_to 'Edit profile | ', edit_user_registration_path, :class => 'page-scroll' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'page-scroll'  %>
            </div>
          <!-- </li> -->
        <% else %>
          <li>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'page-scroll'  %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, :class => 'page-scroll'  %>
          </li>
        <% end %>
        </ul>
        </div>
    </div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
</nav>

<!-- Intro Header -->
<!-- <header class="intro">
    <div class="intro-body">
      <%# yield %> -->
        <!-- <%= image_tag 'logo.png', alt:"", class:"wow fadeIn", data:{wow:{duration:"4s"}}, data:{wow:{delay:".4s"}}  %> -->
        <!-- <img src="img/logo.png" alt="" class="wow fadeIn" data-wow-duration="4s" data-wow-delay=".4s"> -->
        <!-- <div id="clock" class="wow fadeIn" data-wow-duration="6s" data-wow-delay=".6s"></div> -->
        <!-- <p class="intro-text wow fadeIn" data-wow-duration="7s" data-wow-delay=".7s">WE ARE COMING SOON. STAY TUNED!</p> -->
        <!-- <ul class="list-inline lead"> -->
            <!-- <li><a href="#about" class="btn btn-border btn-lg page-scroll wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1.4s"><i class="fa fa-chevron-down"></i> WHO WE ARE</a></li> -->
            <!-- <li><a href="#contact" class="btn btn-white btn-lg page-scroll wow fadeInRight" data-wow-duration="1s" data-wow-delay="1.4s"><i class="fa fa-chevron-down"></i> CONTACT US</a></li> -->
        <!-- </ul> -->
    <!-- </div>
</header> -->

<!-- Action2 Section -->
<section class="action2 container-fluid text-center wow fadeIn">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>Scavenger Hunt</h2>
            <%= yield %>
            <!-- <h3>CSOON IS THE PERFECT THEME FOR YOUR NEXT PROJECT!</h3> -->
            <!-- <p>It’s time to grow your business. Go make something awesome.</p> -->
            <!-- <p><a href="/" class="btn btn-white btn-lg">Get it Now!</a></p> -->
        </div>
    </div>
</section>

<!-- Contact Section -->

<!-- Map Section -->
<!-- <div id="map" class="wow fadeIn"></div> -->

<section id="contact" class="container-fluid text-center wow fadeIn">
    <div class="overlay"></div>
    <div class="row">
        <!-- <div class="col-md-3">
            <h3>(123) 456-7890</h3>
        </div> -->
        <div class="span12">
          Created by Students of Flatiron School<br>
          </i> 11 Broadway New York, NY 10004<br>
          Copyright &copy; Scavenger Hunt NYC 2015
        </div>
        <!-- <div class="col-md-3">
            <ul class="list-inline lead">
                <li><a href="/"><i class="fa fa-twitter fa-fw fa-lg"></i></a></li>
                <li><a href="/"><i class="fa fa-facebook fa-fw fa-lg"></i></a></li>
                <li><a href="/"><i class="fa fa-instagram fa-fw fa-lg"></i></a></li>
                <li><a href="/"><i class="fa fa-envelope fa-fw fa-lg"></i></a></li>
            </ul>
        </div> -->
    </div>
</section>

<%= javascript_include_tag 'application' %>



</body>
</html>

app/views/lists/_new.html.erb
<%= form_tag(lists_path, method: "post", id:"new-list-form") do %>
  <%= text_field_tag(:name, nil, placeholder: 'List Name') %><br>
  <p>&nbsp;</p>
  <%= text_field_tag(:location, nil, placeholder: 'Your Location') %><br>
  <p>&nbsp;</p>
  <%= hidden_field_tag "longitude" %>
  <%= hidden_field_tag "latitude" %>
  <%= submit_tag("Create Hunt", class: "btn btn-white btn-lg") %>
<% end %>

app/views/lists/edit.html.erb
<!-- <div class="container"> -->
  <h1> <%= @list.name %></h1>
  <p>Use this page to edit your list.  If you click one of the X's, you'll delete a clue.  If you click a pencil, you'll get a form to edit a clue.  You can also add clues at the bottom.
  <div class="names-locations">
    <h3>Edit List Info</h3>
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <div id="list-title">
          Title: <%=@list.name %>
        </div>
        <div id="list-location">
          Location: <%=@list.location %>
        </div>
      </div>
      <div class="panel-body">
        <div class= "icon">
          <div id= "edit-list-icon"><%= image_tag("edit.png")%></div>
        </div>
      </div>
      <div id="edit-lists-form-wrapper" style="display:none">
        <%= form_tag("/list/#{@list.id}", method: "post", id:"edit-lists-form") do %>
          <%= hidden_field_tag "list_id", "#{@list.id}" %>
          <%= text_field_tag(:name, nil, value: @list.name) %><br>
          <%= text_field_tag(:location, nil, value: @list.location) %><br>
          <%= submit_tag("Update", class: "btn btn-small") %>
        <% end %>
      </div>
    </div>
  </div>


<!--  STYLING - Please note that any styling that happens below also has to happen on the javascript pages.-->
<h3>Edit Clues For This List</h3>

<div id="clue-list">
  <% if @list.clues.length>0 %>
    <%= render partial:"clues/all_clues" %>
  <% end %>
</div>


<h3>Add A Clue</h3>

<!--  STYLING - Please note that any styling that happens below also has to happen on the javascript pages.-->

<div id="add-clue-wrapper">
  <div id="current_form">
    <!-- <div id="new-clue-form"> -->
      <div class="panel panel-default">
        <div class="panel-heading">
          Use the form below to create a new clue.  You can choose to have us locate your clue based on your current location or to input an address.
        </div>
        <div class="panel-body">
          <%= form_tag("/lists/#{@list.id}/clues", method: "post", id:"new-clue-form") do %>
            <%= text_area_tag(:text, nil, placeholder: 'Your Question', class: "form-control") %><br>
            <%= text_field_tag(:answer, nil, placeholder: 'Enter Answer', class: "form-control") %><br>
            <%= hidden_field_tag "list_id", "#{@list.id}" %>
            <%= hidden_field_tag "longitude" %>
            <%= hidden_field_tag "latitude" %>
            <div id="new-clue-address-form">
              <button id="toggle-address" class="btn btn-small btn-black">Let me input an address.</button>
            </div>
            <div id="submit-new-clue-form">
              <button id="new-clue-form-submit-button" class="btn btn-small btn-black">Create my clue!</button>
              <button id="new-from-address-submit-button" class="hidden btn btn-small btn-black">Create my clue!</button>'
            </div>
        </div>
        <% end %>
    </div>
  <!-- </div> -->

  <div id="new-clue-submit" >
    <%= link_to "Return Home", "/", method:"get", class: "btn btn-small brn-black" %>
  </div>


</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="panel panel-default btn btn-white btn-lg col-xs-12 col-sm-4 action2 container-fluid text-center wow fadeIn">
    <div class="switch-lists-button" id="all-lists-button">
      All Hunts
    </div>
  </div>
  <div class="panel panel-default btn btn-white btn-lg col-xs-12 col-sm-4 action2 container-fluid text-center wow fadeIn">
    <div class="switch-lists-button" id="your-lists-button">
      Hunts You Created
    </div>
  </div>
  <div class="panel panel-default col-xs-12 col-sm-4 action2 container-fluid btn btn-white btn-lg text-center wow fadeIn">
    <div class="">
      <%= link_to "Create Hunt", new_list_path, method:"get" %>
    </div>
  </div>
</div>

<div id="your-lists">
  <% @lists.each do |list| %>
    <% if list.clues.length > 0 && list.creator && list.creator == current_user.id %>
      <div class="col-xs-12 col-sm-6 panel panel-default action2 container-fluid btn btn-white btn-lg text-center wow fadeIn" id="index-button">
        <div class="panel-body">
          <%= link_to "#{list.name}", "/lists/#{list.id}/clues/#{list.clues.first.id}", method:"get" %>
          <br>
          <%= link_to "#{list.location}", "/lists/#{list.id}/clues/#{list.clues.first.id}", method:"get" %>
          <div id="link-to-edit-page panel-body">
            <%= link_to image_tag("white-edit.png"), "/lists/#{list.id}/edit" %>
          </div>
        </div>
      </div>

    <% end %>
  <% end %>
</div>


<div id="all-lists">
  <% @lists.each do |list| %>
    <% if list.clues.length>0 %>
      <div class="col-xs-12 col-sm-6 panel panel-default action2 container-fluid btn btn-white btn-lg text-center wow fadeIn" id="index-button">
        <div class="panel-body" style="min-height: 40; max-height: 40;">
          <%= link_to "#{list.name}", "/lists/#{list.id}/clues/#{list.clues.first.id}", method:"get" %>
          <br>
          <%= link_to "#{list.location}", "/lists/#{list.id}/clues/#{list.clues.first.id}", method:"get" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render partial: 'clues/all_clues' %>
<%= render partial: 'new' %>

app/views/lists/new_from_address.html.erb
<%= form_tag(new_from_address_path, method: "post", id:"new_from_address_form") do %>
  <%= text_field_tag(:name, nil, placeholder: 'List Name') %><br>
  <p>&nbsp;</p>
  <%= text_field_tag(:location, nil, placeholder: 'Your Location', required) %><br>
  <p>&nbsp;</p>
  <%= hidden_field_tag "longitude" %>
  <%= hidden_field_tag "latitude" %>
  <%= submit_tag("Create Hunt", class: "btn btn-white btn-lg") %>
<% end %>